- name:
  hosts: web
  vars: #play level variables
    wishes: Morning
    to: suresh
  tasks:
  - name: print information
    vars:
      to: maduru
    debug:
      msg: "{{to}} Good {{wishes}}"

  - name: print information
    vars:
      to: Jaya
      wishes: Afternoon
    debug:
      msg: "{{to}} Good {{wishes}}"