- name: Prompt vars
  hosts: web
  vars_prompt:
    - name: username
      prompt: please enter username
      private: false
    - name: password
      prompt: please enter password
      private: true
  tasks:
    - name: print
      debug:
        msg: "Hi, {{username}} and {{password}}"